### PR TITLE
Added SLL2 layer decoding

### PR DESCRIPTION
**Pull request by wader**
https://github.com/google/gopacket/pull/933 rebased, regenerated with linter and benchmark commits skipped as i'm not sure they are relevant anymore.

I did a similar PR https://github.com/google/gopacket/pull/1015 sometime ago before i found the one by  @dylandreimerink

Done rudimentary manual testing of pcaps. Should some kind of test(s) be added?

### CODE REVIEW

**Comment by mosajjal** [comment]
just converted some of the travis checks into Github ones. gonna close and reopen this to trigger it :)

**Comment by wader** [comment]
@mosajjal 👍  no worries

**Comment by wader** [comment]
There was no tests in the original PR but i can try add something. What you be a good test, parse some minimal sll2 pcap test file?

**Comment by mosajjal** [comment]
take a look at layers tests like [dns](https://github.com/gopacket/gopacket/blob/master/layers/dns_test.go#L152). For the sake of consistency we can dump the pcap into bytes for testing purposes. makes it easier imo

**Comment by wader** [comment]
Added a test case but only included bytes from sll2 and down, looked like other tests only tested from their layer and down.

**Comment by mosajjal** [comment]
Yep I gather it's the same. looks good to me  :) merged

**Comment by wader** [comment]
Confused, what is this about `Go code is not formatted, run 'go fmt github.com/google/stenographer/...`? should say `go fmt ./...`?

A did a fmt and lots of things changed... but i gess you have a PR for this?

**Comment by wader** [comment]
@mosajjal Aha, good thanks!

**Comment by mosajjal** [comment]
yep that's an old relic from the Google's repo and Travis CI stuff. hopefully all will get removed in a couple days :)

**Comment by wader** [comment]
👍 Great, and thanks for picking up the gopacket development again!

**Pull request merged**
