### PR TITLE
feat: add read support for Name Resolution Block

### PR DESCRIPTION
**Pull request by raphaelcoeffic**

### CODE REVIEW

**Comment by mosajjal** [comment]
Hi, 

thanks for your patience with this PR. I'm keen for us to have `nrb_record_eui48` and `nrb_record_eui64` supported as well. also, `netip.Addr` is preferable to `net.IP` for the record if possible.

**Comment by raphaelcoeffic** [comment]
> I'm keen for us to have `nrb_record_eui48` and `nrb_record_eui64` supported as well. also, `netip.Addr` is preferable to `net.IP` for the record if possible.

Thx for taking a look. I'll add this once I circle back to that. We delayed integrating that feature internally.

**Comment by mosajjal** [comment]
yeah I'm struggling to find good samples as well. but I think so far it looks good to me. we can test it as a PR with different files and see how it works and what would be the best next step.

**Comment by raphaelcoeffic** [comment]
> yeah I'm struggling to find good samples as well. but I think so far it looks good to me. we can test it as a PR with different files and see how it works and what would be the best next step.

Thx, let me know if you need anything.

**Pull request merged**
