### PR TITLE
Using Content-Length to determine SIP message size

### PR DESCRIPTION
**Pull request by thorsager**
As stated in "RFC3261 - 20.14 Content-Length" the header must be used to determine message-size when transporting SIP over TCP.

The Content-Length header is utilized to determine the payload size if it is present, otherwise payload size will be determined by the size of the buffer being parsed.

The setTruncated flag will also be set during parsing if the buffer being parsed does not contain enough data, to honor the Content-Length header.

### CODE REVIEW

**Comment by mosajjal** [comment]
it's RFC RFC3261 not RFC3162

**Comment by mosajjal** [comment]
furthermore, the SIP decoder works regardless of transport layer protocol. but the mandate of content-length is only for TCP not UDP.

**Comment by thorsager** [comment]
> furthermore, the SIP decoder works regardless of transport layer protocol. but the mandate of content-length is only for TCP not UDP.

While that is true the RFC also states:
> Applications SHOULD use this field to indicate the size of the
   message-body to be transferred, regardless of the media type of the
   entity.

Could it not then be argued that if the header is there, it should be used?

**Comment by mosajjal** [comment]
will this break any TCP SIP that doesn't have the content-length header? at the very least there must be some tests for that scenario. I'm reluctant to merge anything breaking especially when it's a "should" in RFC not a MUST

**Comment by thorsager** [comment]
> will this break any TCP SIP that doesn't have the content-length header? at the very least there must be some tests for that scenario. I'm reluctant to merge anything breaking especially when it's a "should" in RFC not a MUST

That makes total sense, they way it has been implemented, it SHOULD not change current behaviour if the header is not there, but I will add tests to ensure this fact.

**Comment by thorsager** [comment]
> will this break any TCP SIP that doesn't have the content-length header? at the very least there must be some tests for that scenario. I'm reluctant to merge anything breaking especially when it's a "should" in RFC not a MUST

On second thought .. the RFC does state that the "Content-Length" header MUST be used when on protocols like TCP
>  The Content-Length header field indicates the size of the message-
   body, in decimal number of octets, sent to the recipient.
   Applications SHOULD use this field to indicate the size of the
   message-body to be transferred, regardless of the media type of the
   entity.  If a stream-based protocol (such as TCP) is used as
   transport, the header field MUST be used.

But as tests currently does not cover decoding any requests without the "Content-Length" header, I will add this, also I will ensure the behavior of the `.GetContentLength()` does not change, compared to the current implementation.

**Comment by thorsager** [comment]
I added one more test to show that length of the message body is only limited when the `Content-Length` header is present in the message. I see no reason in pushing the message through IP and UDP/TCP respectively, as the parser acts the same regardless of the transport.

**Review by mosajjal — APPROVED** [review]

**Review by mosajjal — APPROVED** [review]
looks good now. thanks for your patience. will merge.

**Pull request merged**
