### PR TITLE
Geneve SerializeTo improvements

### PR DESCRIPTION
**Pull request by mejedi**

### CODE REVIEW

**Comment by mosajjal** [comment]
hey thanks for this. can you provide a description of what this does and what current problem you've seen with the current code.

**Comment by mejedi** [comment]
> hey thanks for this. can you provide a description of what this does and what current problem you've seen with the current code.

This adds support for FixLengths option in SerializeTo. Please see commit messages for details.

**Comment by mosajjal** [comment]
thanks. is this ready to merge? happy to merge if so :)

**Comment by mejedi** [comment]
This is ready. Thank you for reviewing.

**Pull request merged**
