### PR TITLE
Fix IPv6 address extraction from Cisco Discovery Protocol v2, fix panics, add fuzzer

### PR DESCRIPTION
**Pull request by TomSellers**
This PR:
- fixes a bug preventing IPv6 addresses from being extracted from CDP. This was due to an incorrect constant value for the IPv6 EtherType. I've added a reference link to the comments. An additional reference can be found [here](https://www.iana.org/assignments/ieee-802-numbers/ieee-802-numbers.xhtml#ieee-802-numbers-1).
- Adds test data to exercise this logic change and demonstrate values.
- Adds a fuzz test and fixes a few panics discovered by it.

Note about fuzzing: The fuzz test was original written for the CDP logic. Since there was nothing constraining the fuzzing to just the CDP logic it started finding panics in other code at a rate of **_about 1 every 5 seconds._**  Since this is out of the scope of this PR and my time is limited I had to stop my work there.  I **_strongly recommend_** running the fuzzer and, after the panics have been addressed, increasing the corpus of packets that seed it.

The command to run the fuzzer is:
`go test -fuzz '^FuzzNewPacket$' github.com/gopacket/gopacket/layers`

### CODE REVIEW

**Comment by TomSellers** [comment]
Depending on how receptive the maintainers are to this, in the future I can try to make timeboxed fuzz+fix passes at the code and submit fixes in batches.

**Comment by TomSellers** [comment]
I just removed `FuzzNewPacket/a9ed54810081738e` from the PR since it was triggering a panic that wasn't fixed in this PR. I think it is fixed in the other PR.

**Comment by mosajjal** [comment]
hey. please decouple the implementation of the fuzzer with the individual fix commits. don't really want to squash merge these together.

**Comment by TomSellers** [comment]
@mosajjal - Can do. I will toss a new clean PR up tomorrow. Any opinions on how you want the other panics PRed? All at once? 1 PR per file/protocol?

**Comment by mosajjal** [comment]
thanks @TomSellers. as for each of the panics, if any panic can happen as a result of an external packet being processed, it should be treated as a CVE and each should have separate security advisories. please don't put them in public PRs just yet and I'll figure out a way to provide advisories and CVE numbers for them.

**Comment by TomSellers** [comment]
Closing this PR. I will open new PRs as requested.

**Pull request closed without merging**
