### PR TITLE
Changing internal type of CSEQ and Content-Length

### PR DESCRIPTION
**Pull request by thorsager**
Prior to this int64 have been used to store the values, this requires some, perhaps unsafe "truncation" of contentLength when mapping to the internal buffer for storing payload.

I have changed the internal type to better fit the usage of the values, and added guard checks when parsing.

To better test for parsing-errors I have refactored testing.

### CODE REVIEW

**Comment by mosajjal** [comment]
@thorsager thanks for this. since we don't use testify in this lib (yet), I commented them out and replaced them with a basic equivalent using stdlib. can you confirm if the tests still work?

**Comment by thorsager** [comment]
> @thorsager thanks for this. since we don't use testify in this lib (yet), I commented them out and replaced them with a basic equivalent using stdlib. can you confirm if the tests still work?

It looks as though the `Subset` tests are not working as expected, I'll have a look and update :) .. Thank you for getting this started.. I hop to get it done later today :)

**Comment by thorsager** [comment]
@mosajjal anything I can do to move this one along?

**Comment by mosajjal** [comment]
been too busy to take a look at this repo lately. hopefully I'll get some time over the weekend to review the code.

**Comment by thorsager** [comment]
No worries 💪🙂

**Review by mosajjal — APPROVED** [review]

**Comment by mosajjal** [comment]
good stuff. merged!

**Pull request merged**
